language: python

jobs:
    include:
        # Linux
        - services: docker
        # OSX
        - os: osx
          language: shell
        # Windows
        - os: windows
          language: shell
          before_install:
            - choco install python --version 3.8.0
            - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"

env:
    global:
        - TWINE_USERNAME=__token__
        # TWINE_PASSWORD is set in Travis settings

before_install:
    - ls
    - pwd
    - cd ../
    - git clone --recurse-submodules https://github.com/pydicom/pylibjpeg
    - cd pylibjpeg

install:
    - python3 -m pip install cibuildwheel==1.1.0

script:
    - python3 -m cibuildwheel --output-dir wheelhouse

after_success:
    - ls wheelhouse
    # If the release was tagged, upload to PyPI
    #- |
    #    if [[ $TRAVIS_TAG ]]; then
    #        python3 -m pip install twine
    #        python3 -m twine upload wheelhouse/*.whl
    #    fi
