branches:
    only:
        - "master"

language: python

jobs:
    include:
        # Linux - working
        - services: docker
          name: Linux
          python: "3.8"
          env:
            - PYEXE=python3
            - WHEELHOUSE_TAR=wheelhouse-linux.tar.gz
        # ARMv8 - not working
        #- services: docker
        #  arch: aarch64
        #  python: "3.8"
        #  env: PYEXE=python3
        # PPC64LE - not working
        #- services: docker
        #  arch: ppc641le
        #  python: "3.8"
        #  env: PYEXE=python3
        # OSX - working
        - os: osx
          name: OSX
          language: shell
          python: "3.8"
          env:
            - PYEXE=python3
            - WHEELHOUSE_TAR=wheelhouse-osx.tar.gz
        # Windows
        - os: windows
          name: Windows
          language: shell
          env:
            - PYEXE=/c/Python38/python
            - LIB=/c/Python38/libs
            - WHEELHOUSE_TAR=wheelhouse-win.tar.gz
          before_install:
            # We're going to use MSVC VisualStudio 2017's build tools
            - choco install python --version 3.8
            - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"

env:
    global:
        - CIBW_BUILD="cp36-* cp37-* cp38-*"

install:
    - $PYEXE -m pip install cibuildwheel==1.1.0
    - cd ../
    - git clone --recurse-submodules https://github.com/pydicom/pylibjpeg-libjpeg
    - cd pylibjpeg-libjpeg
    - $PYEXE -m pip install cython numpy
    - $PYEXE -m pip install .

script:
    - $PYEXE -m cibuildwheel --output-dir wheelhouse

after_success:
    # Upload wheels to transfer.sh
    - ls wheelhouse
    - tar czf wheelhouse.tar.gz wheelhouse
    - sha256sum wheelhouse.tar.gz
    - rtn=$(curl --upload-file ./wheelhouse.tar.gz https://transfer.sh/$WHEELHOUSE_TAR)
    - echo $rtn
